// Legacy Jenkinsfile — references Bitbucket for shared library
@Library('https://sourcecode.ana.corp.aviva.com/scm/apa/jenkins-shared-library@main') _

pipeline {
    agent any
    stages {
        stage('Init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('Apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}
